import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // Layer boundary: the UI layer must never import domain logic directly.
    // It reads state from the reducer and dispatches actions, nothing more.
    files: ['src/components/**/*.{ts,tsx}', 'src/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/domain/*', '**/domain/*'],
              message:
                'UI must not import domain logic directly - read state from the reducer instead. ' +
                'The single exception is StrategyChart.tsx, which renders the lookup tables ' +
                'themselves so the chart can never drift from the evaluator.',
            },
          ],
        },
      ],
    },
  },
  {
    // The allowlisted exception, see the message above.
    files: ['src/components/StrategyChart.tsx'],
    rules: { 'no-restricted-imports': 'off' },
  },
  {
    // The domain layer is pure: no React, no browser APIs, no storage.
    files: ['src/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['react', 'react-dom', 'next/*', '@/storage/*', '@/game/*'],
              message: 'domain/ must stay pure - no React, storage, or game-state imports.' },
          ],
        },
      ],
    },
  },
  // next-env.d.ts is generated by Next on every build; config files are
  // module-shaped by convention. Neither is source we control.
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      '*.config.mjs',
      '*.config.ts',
      '*.config.mts',
    ],
  },
];
